### ISSUE TITLE
Registry component isn't reactive initially

### ISSUE THREAD

**Issue by AtHeartEngineer** [Rate-Limiting-Nullifier/rlnjs-demo#3]
![image](https://user-images.githubusercontent.com/1675654/227141436-f1da0092-3d79-40f2-83ff-34e6a5875af1.png)
Id Commitment Registry is empty until you change anything else and then it refreshes.

**Comment by NicoSerranoP** [comment]
I feel it might be related to reactivity of the registry object itself. `Registry` contains `members` but these are updated after the instance compute the proofs. I think SolidJS is not detecting those changes therefore the info is not being showed. When you do a code change, the HTML refreshes and shows the `Registry` object data with the actual `members`.

 (maybe change `createSignal` for `createStore`? I tried but didn't work. I would give it a try tomorrow)

**Comment by NicoSerranoP** [comment]
I know how to fix it! :D give a moment
